# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(538, 310)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_deposit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_deposit.setGeometry(QtCore.QRect(250, 30, 75, 23))
        self.pushButton_deposit.setObjectName("pushButton_deposit")
        self.pushButton_withdraw = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_withdraw.setGeometry(QtCore.QRect(350, 30, 75, 23))
        self.pushButton_withdraw.setObjectName("pushButton_withdraw")
        self.pushButton_create_account = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_create_account.setGeometry(QtCore.QRect(10, 190, 111, 31))
        self.pushButton_create_account.setObjectName("pushButton_create_account")
        self.listWidget_accounts = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget_accounts.setGeometry(QtCore.QRect(10, 30, 191, 151))
        self.listWidget_accounts.setObjectName("listWidget_accounts")
        self.pushButton_delete_account = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_delete_account.setGeometry(QtCore.QRect(130, 190, 111, 31))
        self.pushButton_delete_account.setObjectName("pushButton_delete_account")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 61, 16))
        self.label.setObjectName("label")
        self.pushButton_set_balance = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_set_balance.setGeometry(QtCore.QRect(440, 30, 75, 23))
        self.pushButton_set_balance.setObjectName("pushButton_set_balance")
        self.listView_updates = QtWidgets.QListView(parent=self.centralwidget)
        self.listView_updates.setGeometry(QtCore.QRect(250, 60, 271, 201))
        self.listView_updates.setObjectName("listView_updates")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 230, 111, 31))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 538, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_deposit.setText(_translate("MainWindow", "Deposit"))
        self.pushButton_withdraw.setText(_translate("MainWindow", "Withdraw"))
        self.pushButton_create_account.setText(_translate("MainWindow", "Account"))
        self.pushButton_delete_account.setText(_translate("MainWindow", "Delete Account"))
        self.label.setText(_translate("MainWindow", "Accounts"))
        self.pushButton_set_balance.setText(_translate("MainWindow", "Set Balance"))
        self.pushButton.setText(_translate("MainWindow", "Saving Account"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
