# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(349, 211)
        Dialog.setMinimumSize(QtCore.QSize(349, 211))
        Dialog.setMaximumSize(QtCore.QSize(349, 211))
        self.lineEdit_username = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_username.setGeometry(QtCore.QRect(120, 40, 171, 21))
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.lineEdit_password = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_password.setGeometry(QtCore.QRect(120, 90, 171, 21))
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.label_username = QtWidgets.QLabel(parent=Dialog)
        self.label_username.setGeometry(QtCore.QRect(50, 40, 61, 16))
        self.label_username.setObjectName("label_username")
        self.label_password = QtWidgets.QLabel(parent=Dialog)
        self.label_password.setGeometry(QtCore.QRect(50, 90, 61, 16))
        self.label_password.setObjectName("label_password")
        self.pushButton_login = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_login.setGeometry(QtCore.QRect(80, 160, 75, 23))
        self.pushButton_login.setObjectName("pushButton_login")
        self.pushButton_cancel = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_cancel.setGeometry(QtCore.QRect(190, 160, 75, 23))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.label_username_hint = QtWidgets.QLabel(parent=Dialog)
        self.label_username_hint.setGeometry(QtCore.QRect(120, 70, 47, 13))
        self.label_username_hint.setObjectName("label_username_hint")
        self.label_password_hint = QtWidgets.QLabel(parent=Dialog)
        self.label_password_hint.setGeometry(QtCore.QRect(120, 120, 61, 16))
        self.label_password_hint.setObjectName("label_password_hint")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_username.setText(_translate("Dialog", "Username"))
        self.label_password.setText(_translate("Dialog", "Password"))
        self.pushButton_login.setText(_translate("Dialog", "Login"))
        self.pushButton_cancel.setText(_translate("Dialog", "Cancel"))
        self.label_username_hint.setText(_translate("Dialog", "(admin)"))
        self.label_password_hint.setText(_translate("Dialog", "(password)"))
